# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: daily
    labels:
      - Dependencies
      - CI/CD
    open-pull-requests-limit: 100

  - package-ecosystem: cargo
    directory: /
    target-branch: main
    schedule:
      interval: daily
    labels:
      - Dependencies
    open-pull-requests-limit: 100
