[package]
name = "demon-bluff-logic-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
demon-bluff-gameplay-engine = { path = "../demon-bluff-gameplay-engine" }
force_graph = { git = "https://github.com/t-mw/force-graph-rs" }
enum_delegate = "0.2.0"
thiserror = "2.0.16"
